import {useEffect,useRef,useState,type MutableRefObject} from 'react'
import {DEFAULT_COUPLED,PRESETS,type CoupledInputs,type CoupledFrame,type Fidelity} from '../coupled/model'
import CoupledWorker from '../worker/coupled.worker.ts?worker'
import {ModelSelector,type PhysicsWorkspace} from './ModelSelector'
import {ParameterSlider} from './ParameterSlider'
import {CoupledScene,COUPLED_FIELDS,type CoupledField} from './CoupledScene'
import './coupled.css'
interface Run {status?:string;message?:string;mode:string;frames:CoupledFrame[];setupMs:number;solveMs:number;couplingIterations:number;mechanicalBalanceJ:number;referenceBoundaryWorkJ:number;geostaticResidualN:number}
export interface CoupledSession {inputs:CoupledInputs;runs:Record<string,Run>;index:number;field:CoupledField;cut:boolean;context:boolean;amplification:number;compare:boolean;mode:string}
export default function CoupledWorkspace({onWorkspace,session}:{onWorkspace:(v:PhysicsWorkspace)=>void;session:MutableRefObject<CoupledSession|undefined>}){
 const saved=session.current,[inputs,setInputs]=useState(saved?.inputs??{...DEFAULT_COUPLED}),[runs,setRuns]=useState<Record<string,Run>>(saved?.runs??{}),[index,setIndex]=useState(saved?.index??0),[field,setField]=useState<CoupledField>(saved?.field??'temperatureK'),[cut,setCut]=useState(saved?.cut??true),[context,setContext]=useState(saved?.context??true),[amplification,setAmplification]=useState(saved?.amplification??1),[compare,setCompare]=useState(saved?.compare??false),[mode,setMode]=useState(saved?.mode??'coupled')
 const [running,setRunning]=useState(false),[status,setStatus]=useState('Ready to calculate'),[error,setError]=useState(''),[live,setLive]=useState<CoupledFrame>(),[playing,setPlaying]=useState(false),[probe,setProbe]=useState(0),[throughput,setThroughput]=useState(0)
 const worker=useRef<Worker|null>(null),run=runs[mode],frame=running?live:run?.frames[Math.min(index,run.frames.length-1)],grid=PRESETS[inputs.fidelity],info=COUPLED_FIELDS[field]
 useEffect(()=>{session.current={inputs,runs,index,field,cut,context,amplification,compare,mode}},[inputs,runs,index,field,cut,context,amplification,compare,mode,session])
 useEffect(()=>()=>worker.current?.terminate(),[])
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setIndex(i=>{if(i>=(run?.frames.length??1)-1){setPlaying(false);return i}return i+1}),100);return()=>clearInterval(id)},[playing,run])
 const stop=()=>{worker.current?.terminate();worker.current=null;setRunning(false);setPlaying(false);setStatus('Calculation stopped; completed runs retained')}
 const update=(next:CoupledInputs)=>{stop();setInputs(next);setRuns({});setLive(undefined);setIndex(0);setError('');setStatus('Physical inputs changed · recompute required')}
 const calculate=()=>{stop();setRuns({});setLive(undefined);setIndex(0);setError('');setRunning(true);setStatus('Initializing equilibrium…');const w=new CoupledWorker();worker.current=w
  w.onmessage=e=>{if(worker.current!==w)return;const data=e.data
   if(data.type==='progress'){setLive(data.frame);setStatus(`${data.mode==='rigid'?'Rigid-pore comparison':'Coupled scenario'} · ${data.timeS.toFixed(1)} / ${inputs.durationS} s`);setThroughput(data.timeS/(data.elapsedMs/1000))}
   if(data.type==='result'){setRuns(old=>({...old,[data.mode]:data}));setIndex(data.frames.length-1)}
   if(data.type==='done'){setRunning(false);setStatus('Complete · numerical reference, uncalibrated site');w.terminate();worker.current=null;setIndex(60)}
   if(data.type==='error'){setRunning(false);setError(data.message);setStatus('Stopped at validity or convergence limit');w.terminate();worker.current=null}}
  w.onerror=e=>{setError(e.message);setRunning(false);w.terminate();worker.current=null};w.postMessage({inputs,compare})}
 const download=()=>{const text=JSON.stringify({format:'zombie-coupled',version:1,inputs,runs,scope:'3D thermoporoelastic model; diffuse brittle fracture is research. Root trusses assumed. Detailed oak/root anatomy and borehole are illustrative; the cap is a computed reduced shell/contact model. No matched experimental validation.'},(_,v)=>ArrayBuffer.isView(v)?Array.from(v as unknown as ArrayLike<number>):v,2),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='coupled-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="ops-shell coupled-shell"><header className="ops-header"><div className="ops-brand"><strong>ZOMBIE FIRE</strong><span>COUPLED CONTINUUM / 0.11</span></div><ModelSelector value="coupled" onChange={onWorkspace}/><button className="ops-secondary" onClick={download} disabled={!run}>Export calculation</button></header>
 <div className="ops-title"><div><span className="ops-eyebrow">THERMAL · GAS · WATER · EFFECTIVE STRESS</span><h1>One scenario. Coupled physics.</h1></div><span className="ops-status">{running?'CALCULATING':'RESEARCH MODEL'}<i/></span></div>
 <main className="coupled-main"><aside className="ops-controls"><h2>Physical scenario</h2><p>8 × 8 × 3.2 m. Finite inventories and initialized gravity. A prepared dry hot region supplies ignition energy in the initial state.</p>
 <label>Fidelity<select aria-label="Coupled fidelity" value={inputs.fidelity} onChange={e=>update({...inputs,fidelity:e.target.value as Fidelity})}>{Object.entries(PRESETS).map(([key,p])=><option key={key} value={key}>{key} · {p.nx*p.ny*p.nz} cells</option>)}</select></label>
 <button className="ops-primary" onClick={running?stop:calculate}>{running?'Cancel calculation':'Calculate coupled scenario'}</button><p role="status">{status}</p>{error&&<p role="alert" className="coupled-error">{error}</p>}
 <ParameterSlider label="Simulation duration" value={inputs.durationS} min={10} max={3600} step={10} unit="s" defaultValue={120} onChange={v=>update({...inputs,durationS:v})}/>
 <ParameterSlider label="Dry ice inventory" value={inputs.dryIceKg} min={0} max={20} step={0.1} unit="kg" defaultValue={4} onChange={v=>update({...inputs,dryIceKg:v})}/>
 <ParameterSlider label="Heater power" value={inputs.heaterW} min={0} max={500} step={1} unit="W" defaultValue={0} onChange={v=>update({...inputs,heaterW:v})}/>
 <ParameterSlider label="Peat water saturation" value={inputs.moisture} min={0} max={0.8} step={0.01} unit="pore fraction" defaultValue={0.2} onChange={v=>update({...inputs,moisture:v})}/>
 <label><input type="checkbox" checked={inputs.reaction} onChange={e=>update({...inputs,reaction:e.target.checked})}/> Oxygen-limited oxidation</label>
 <label><input type="checkbox" checked={inputs.mechanics} onChange={e=>update({...inputs,mechanics:e.target.checked})}/> Two-way deformation and pressure work</label>
 <label><input type="checkbox" checked={inputs.cap} onChange={e=>update({...inputs,cap:e.target.checked})}/> Seated cap · shallow shell and rim contact</label>
 <label><input type="checkbox" checked={inputs.roots} onChange={e=>update({...inputs,roots:e.target.checked})}/> Embedded root trusses · assumed properties</label>
 <label><input type="checkbox" checked={compare} onChange={e=>{stop();setCompare(e.target.checked)}}/> Calculate same scenario with rigid pores</label>
 <details className="ops-details"><summary>Developer tools</summary><ParameterSlider label="Cap diameter" value={2*inputs.capRadiusM} min={0.5} max={2} step={0.05} unit="m" defaultValue={0.95} onChange={v=>update({...inputs,capRadiusM:v/2,capRiseM:Math.min(inputs.capRiseM,0.15*v)})}/><ParameterSlider label="Cap rise" value={inputs.capRiseM} min={0.02} max={Math.min(0.2,0.3*inputs.capRadiusM)} step={0.01} unit="m" defaultValue={0.1} onChange={v=>update({...inputs,capRiseM:v})}/><ParameterSlider label="Cap thickness" value={1000*inputs.capThicknessM} min={1} max={10} step={0.5} unit="mm" defaultValue={5} note="Assumed elastic steel; rim anchors uncalibrated" onChange={v=>update({...inputs,capThicknessM:v/1000})}/><ParameterSlider label="Peat elastic modulus" value={inputs.youngsPa/1e6} min={0.5} max={10} step={0.1} unit="MPa" defaultValue={1} note="Uncalibrated" onChange={v=>update({...inputs,youngsPa:v*1e6})}/><ParameterSlider label="Vertical permeability" value={inputs.permeabilityM2/1e-12} min={0.1} max={100} step={0.1} unit="10⁻¹² m²" defaultValue={8} onChange={v=>update({...inputs,permeabilityM2:v*1e-12})}/><label><input type="checkbox" checked={inputs.fracture} onChange={e=>update({...inputs,fracture:e.target.checked})}/> Spatial phase-field fracture · research</label><ParameterSlider label="Fracture energy" value={inputs.fractureEnergyJm2} min={1} max={100} step={1} unit="J/m²" defaultValue={5} note="Unmeasured; no calibrated strength" onChange={v=>update({...inputs,fractureEnergyJm2:v})}/><ParameterSlider label="Fracture length scale" value={inputs.lengthScaleM} min={0.2} max={2} step={0.1} unit="m" defaultValue={1} note="Need cell spacing ≤ length / 2 for resolved crack band" onChange={v=>update({...inputs,lengthScaleM:v})}/></details>

 </aside><section className="coupled-view"><div className="coupled-render"><label>Rendering<select aria-label="Coupled field" value={field} onChange={e=>setField(e.target.value as CoupledField)}>{Object.entries(COUPLED_FIELDS).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></label><label><input type="checkbox" checked={cut} onChange={e=>setCut(e.target.checked)}/> Cutaway</label><label><input type="checkbox" checked={context} onChange={e=>setContext(e.target.checked)}/> Scene context</label><label>Displacement display<select aria-label="Displacement display" value={amplification} onChange={e=>setAmplification(Number(e.target.value))}>{[1,10,100].map(n=><option key={n} value={n}>{n}×</option>)}</select></label>{runs.rigid&&<label>Model<select aria-label="Coupled comparison" value={mode} onChange={e=>{const target=e.target.value,frames=runs[target]?.frames;if(frames&&frame){let closest=0;for(let i=1;i<frames.length;i++)if(Math.abs(frames[i].timeS-frame.timeS)<Math.abs(frames[closest].timeS-frame.timeS))closest=i;setIndex(closest)}setMode(target)}}><option value="coupled">Coupled pores</option><option value="rigid">Rigid ground and cap · same inputs</option></select></label>}</div>
 <div className="coupled-canvas"><CoupledScene capEnabled={inputs.cap} capRadius={inputs.capRadiusM} capRise={inputs.capRiseM} frame={frame} fidelity={inputs.fidelity} field={field} cut={cut} context={context} amplification={amplification} onProbe={setProbe}/><div className="coupled-legend">{info.label} · {info.unit}<div/>{info.range[0]} — {info.range[1]}<br/>Oak anatomy and borehole: illustrative context.<br/>Terrain deformation: calculated, {amplification}× display. Cap: reduced shell at 1×.<br/>Fixed scale; end colors include values outside the range.</div></div>
 <div className="coupled-timeline"><button onClick={()=>setPlaying(!playing)} disabled={!run||running}>{playing?'Pause replay':'Replay'}</button><input aria-label="Coupled replay time" type="range" min={0} max={Math.max(0,(run?.frames.length??1)-1)} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value))}} disabled={running||!run}/><strong>{(frame?.timeS??0).toFixed(2)} s</strong></div>
 <div className="coupled-instruments"><div><span>Throughput</span><strong>{(running?throughput:run?(run.frames.at(-1)?.timeS??0)/(run.solveMs/1000):0).toFixed(1)} sim s / wall s</strong></div><div><span>Cell {probe} · {info.label}</span><strong>{frame?.[field][probe]?.toPrecision(6)??'—'} {info.unit}</strong></div><div><span>Dry ice remaining</span><strong>{frame?.dryIceKg.toFixed(6)??'—'} kg</strong></div><div><span>Thermal + phase energy residual</span><strong>{frame?.ledger.energyResidualJ.toExponential(2)??'—'} J</strong></div><div><span>Total mass residual</span><strong>{frame?.ledger.massResidualKg.toExponential(2)??'—'} kg</strong></div><div><span>Mechanical force residual</span><strong>{frame?.mechanical?.residualN.toExponential(2)??'—'} N</strong></div><div><span>Incremental principal strain</span><strong>{frame?.mechanical?(frame.mechanical.maxStrain*100).toFixed(5):'—'} %</strong></div><div><span>Cap contact / flex</span><strong>{frame?.cap?`${frame.cap.contactN.toFixed(2)} N / ${(frame.cap.flexM*1e6).toFixed(3)} µm`:"—"}</strong></div><div><span>Pressure work / mechanics mismatch</span><strong>{run?.mechanicalBalanceJ.toExponential(2)??'—'} J</strong></div></div>
 <details className="coupled-scope"><summary>Model status and validation gaps</summary><p>Implemented: four gas species, compressible Darcy storage, anisotropic permeability, gas enthalpy, water phase equilibrium, finite dry ice, oxidation, heterogeneous 3D elastic effective stress, gravity preload, pore-volume feedback and embedded axial roots and a shallow cap shell with rim contact/anchors. Spatial brittle fracture uses a diffuse energy regularization and tension/compression split. It is not a calibrated peat failure law.</p><p>Fracture verification has not passed: the spatial mesh-energy difference is about 5.74% against a 5% gate, and the default coupled fracture attempt fails its energy-increment gate (about 4.99 J). Fracture is off by default. A failed run retains only accepted states; a complete terrain rupture path is unresolved.</p><p>Remaining: matched peat kinetics/mechanics/fracture data; char and pyrolysis; liquid-water flow, cryosuction and ice heave; finite deformation, sharp crack separation and frictional contact; general nonlinear shell contact and a resolved borehole conduit; creep and calibrated root pullout. A 2% strain guard and Darcy regime checks stop unsupported runs. No field suppression or rupture prediction is experimentally validated. Preview crack bands can be under-resolved.</p><p>{grid.nx} × {grid.ny} × {grid.nz} cells. Replay is bounded to 61 regular frames plus a terminal failure frame per model. Camera, field and replay controls preserve the trajectory.</p></details>
 </section></main></div>
}
