import { useEffect, useMemo, useRef, useState, type MutableRefObject } from 'react'
import { ModelSelector, type PhysicsWorkspace } from './ModelSelector'
import { FireSequenceScene, type FireFieldSnapshot, type FireSequenceLayers } from './FireSequenceScene'
import { FIRE_SEQUENCE_DURATION as DURATION, FIRE_SEQUENCE_STAGES as STAGES, sequenceStage, acceptedFireFrame, illustratedPeatCoverage, storyToPlayback, playbackToStory, FIRE_SEQUENCE_PLAYBACK_DURATION, type FireSourceMode, type FireSequenceView } from '../story/fireSequence'
import type { FireProtocolCache } from '../coupled/fireProtocolRunner'
import { FireExperimentControls, DEFAULT_FIRE_SETTINGS, type FireExperimentSettings } from './FireExperimentControls'
import './fire-sequence.css'

export type ProtocolCache = FireProtocolCache
export interface FireSequenceSession { time:number;speed:number;mode:FireSourceMode;view:FireSequenceView;layers:FireSequenceLayers;loop:boolean;cache?:ProtocolCache;settings?:FireExperimentSettings }
const clock=(seconds:number)=>seconds>=3600?`${(seconds/3600).toFixed(2)} h`:seconds>=60?`${(seconds/60).toFixed(1)} min`:`${seconds.toFixed(1)} s`
function validCache(value:unknown):value is ProtocolCache {
  if(!value||typeof value!=='object')return false
  const cache=value as ProtocolCache,d=cache.domain,n=d?d.nx*d.ny*d.nz:0
  if(cache.schemaVersion!==1||cache.kind!=='surface-ignition-protocol'||!d||![d.nx,d.ny,d.nz].every(value=>Number.isInteger(value)&&value>0)||n>100000||d.widthM!==8||d.lengthM!==8||d.depthM!==3.2||!Array.isArray(cache.frames)||!cache.frames.length)return false
  return cache.frames.every((frame,index)=>Number.isFinite(frame.timeS)&&frame.timeS>=0&&(index===0||frame.timeS>=cache.frames[index-1].timeS)&&Number.isFinite(frame.dryIceKg)&&[frame.temperatureK,frame.oxygen,frame.co2].every(values=>Array.isArray(values)&&values.length===n&&values.every(Number.isFinite))&&(!frame.metrics||[frame.metrics.maxTemperatureK,frame.metrics.reactedFuelKg].every(Number.isFinite)))
}
export default function FireSequenceWorkspace({onWorkspace,session}:{onWorkspace:(workspace:PhysicsWorkspace)=>void;session?:MutableRefObject<FireSequenceSession|undefined>}){
  const saved=session?.current,[time,setTime]=useState(saved?.time??0),[speed,setSpeed]=useState(saved?.speed??1),[mode,setMode]=useState<FireSourceMode>(saved?.mode??'gradual'),[view,setView]=useState<FireSequenceView>(saved?.view??'natural')
  const [playing,setPlaying]=useState(false),[loop,setLoop]=useState(saved?.loop??false),[layers,setLayers]=useState<FireSequenceLayers>(saved?.layers??{fire:true,gas:true,water:true,anatomy:true}),[resetToken,setResetToken]=useState(0),[cache,setCache]=useState<ProtocolCache|undefined>(saved?.cache),[cacheStatus,setCacheStatus]=useState('Loading accepted calculation…')
  const [presentation,setPresentation]=useState<'interactive'|'film'>('interactive'),[filmReady,setFilmReady]=useState(false),[filmRefresh,setFilmRefresh]=useState(0),[filmError,setFilmError]=useState(false)
  const videoRef=useRef<HTMLVideoElement>(null),bundledCache=useRef<ProtocolCache|undefined>(undefined),acceptedCacheRef=useRef(saved?.cache)
  const [settings,setSettings]=useState<FireExperimentSettings>(saved?.settings??DEFAULT_FIRE_SETTINGS)
  const timeRef=useRef(time),stage=sequenceStage(time),stageIndex=STAGES.findIndex(item=>item.id===stage.id)
  useEffect(()=>{if(session)session.current={time,speed,mode,view,layers,loop,cache,settings}},[session,time,speed,mode,view,layers,loop,cache,settings])
  useEffect(()=>{
    const controller=new AbortController()
    fetch(`${import.meta.env.BASE_URL}fire-sequence-cache.json`,{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error('cache unavailable');return response.json()}).then(value=>{if(!validCache(value))throw new Error('cache format mismatch');bundledCache.current=value;if(!acceptedCacheRef.current){acceptedCacheRef.current=value;setCache(value);setCacheStatus('Bundled numerical history loaded')}else setCacheStatus('Retained numerical history loaded')}).catch(error=>{if(error.name!=='AbortError')setCacheStatus(acceptedCacheRef.current?'Retained history available · bundled reference unavailable':'Numerical history unavailable · story remains illustrative')})
    return()=>controller.abort()
  },[])
  useEffect(()=>{
    const controller=new AbortController()
    fetch(`${import.meta.env.BASE_URL}renders/manifest.json`,{signal:controller.signal}).then(response=>response.ok?response.json():null).then(value=>{setFilmReady(value?.ready===true&&value?.films?.gradual?.file==='peat-fire-gradual.mp4'&&value?.films?.rapid?.file==='peat-fire-rapid.mp4');setFilmError(false)}).catch(()=>setFilmReady(false))
    return()=>controller.abort()
  },[filmRefresh])
  useEffect(()=>{
    if(!playing)return
    let request=0,last=performance.now(),paint=last
    const tick=(now:number)=>{const elapsed=Math.min(.2,(now-last)/1000);last=now;timeRef.current=playbackToStory(storyToPlayback(timeRef.current)+elapsed*speed);if(timeRef.current>=DURATION){if(loop)timeRef.current=0;else{timeRef.current=DURATION;setTime(DURATION);setPlaying(false);return}}if(now-paint>=1000/30){setTime(timeRef.current);paint=now}request=requestAnimationFrame(tick)}
    request=requestAnimationFrame(tick);return()=>cancelAnimationFrame(request)
  },[playing,speed,loop])
  const seek=(next:number)=>{const bounded=Math.max(0,Math.min(DURATION,next));timeRef.current=bounded;setTime(bounded);if(presentation==='film'&&videoRef.current&&Number.isFinite(videoRef.current.duration))videoRef.current.currentTime=storyToPlayback(bounded)/FIRE_SEQUENCE_PLAYBACK_DURATION*videoRef.current.duration}
  const play=()=>{if(time>=DURATION)seek(0);setPlaying(value=>!value)}
  const displayCache=presentation==='film'?bundledCache.current:cache
  const cacheFrame=useMemo(()=>displayCache?acceptedFireFrame(displayCache.frames,mode==='rapid'&&time>=55?54.9:time,displayCache.ignitionEndS):undefined,[displayCache,time,mode])
  const fieldFrame=useMemo<FireFieldSnapshot|undefined>(()=>displayCache&&cacheFrame?{...cacheFrame,dryIceKg:cacheFrame.phase==='treatment'?cacheFrame.dryIceKg:undefined,nx:displayCache.domain.nx,ny:displayCache.domain.ny,nz:displayCache.domain.nz}:undefined,[displayCache,cacheFrame])
  const gap=time>=69?'Water and cracks are an assumed visualization. Liquid infiltration and fracture-driven flow are not solved.':mode==='rapid'&&time>=55?'Rapid conversion is a prescribed illustration. Numerical fields and readouts hold the accepted pre-treatment state.':'Drilling, source placement and enlarged dome bending are staged geometry, not solved operations.'
  const coverage=illustratedPeatCoverage(time)
  const stageSymbols=['✦','≈','↓','●','⌒','↗','≋','◉']
  return <div className="fire-sequence-shell">
    <header className="fire-sequence-header"><div className="fire-sequence-brand"><span>Z</span><div><strong>ZOMBIE FIRE</strong><small>THE COMPLETE SEQUENCE</small></div></div><ModelSelector value={'sequence' as PhysicsWorkspace} onChange={onWorkspace}/><button className="fire-lab-link" onClick={()=>onWorkspace('coupled')}>Open physics lab ↗</button></header>
    <main className="fire-sequence-main">
      <aside className="fire-sequence-rail"><div className="fire-story-title"><span>FROM IGNITION TO INTERVENTION</span><h1>Follow the fire<br/>beneath the surface.</h1><p>A continuous visual sequence with a separate, inspectable numerical history.</p></div><div className="fire-mode-switch" role="group" aria-label="Dry ice conversion presentation"><button aria-pressed={mode==='gradual'} onClick={()=>setMode('gradual')}><strong>Gradual</strong><span>Calculated source mass</span></button><button aria-pressed={mode==='rapid'} onClick={()=>setMode('rapid')}><strong>Rapid</strong><span>Illustrative conversion</span></button></div><nav className="fire-stage-list" aria-label="Sequence chapters">{STAGES.map((item,i)=><button key={item.id} aria-current={i===stageIndex?'step':undefined} className={i<stageIndex?'is-past':''} onClick={()=>{setPlaying(false);seek(item.start)}}><span className="fire-stage-number">{i<stageIndex?'✓':String(i+1).padStart(2,'0')}</span><span><strong>{item.short}</strong><small>{item.start}–{item.end} s presentation</small></span><i>{stageSymbols[i]}</i></button>)}</nav><p className="fire-story-scope">The story clock compresses events. It is not the physical clock or a field treatment procedure.</p></aside>
      <section className="fire-sequence-experience" aria-label="Full fire and treatment animation"><div className="fire-sequence-toolbar"><div className="fire-presentation-switch" role="group" aria-label="Sequence presentation"><button aria-pressed={presentation==='interactive'} onClick={()=>setPresentation('interactive')}>Interactive</button><button aria-pressed={presentation==='film'} onClick={()=>{setPlaying(false);setPresentation('film')}}>Rendered film</button></div><div className="fire-view-switch" role="group" aria-label="Sequence view">{([['natural','Natural cutaway'],['temperature','Temperature'],['oxygen','Oxygen'],['co2','CO₂']] as const).map(([key,label])=><button key={key} disabled={presentation==='film'} aria-pressed={view===key} onClick={()=>setView(key)}>{label}</button>)}</div><button className="fire-camera-reset" onClick={()=>setResetToken(value=>value+1)}>↺ Reset camera</button></div>
        <div className="fire-sequence-canvas">{presentation==='interactive'?<FireSequenceScene time={time} mode={mode} view={view} layers={layers} frame={fieldFrame} resetToken={resetToken}/>:filmReady&&!filmError?<video ref={videoRef} key={mode} className="fire-rendered-video" controls playsInline preload="metadata" src={`${import.meta.env.BASE_URL}renders/peat-fire-${mode}.mp4`} onLoadedMetadata={event=>{event.currentTarget.currentTime=storyToPlayback(timeRef.current)/FIRE_SEQUENCE_PLAYBACK_DURATION*event.currentTarget.duration;event.currentTarget.playbackRate=speed}} onTimeUpdate={event=>{const element=event.currentTarget;if(element.duration>0){timeRef.current=playbackToStory(element.currentTime/element.duration*FIRE_SEQUENCE_PLAYBACK_DURATION);setTime(timeRef.current)}}} onError={()=>setFilmError(true)} loop={loop}/>:<div className="fire-film-placeholder"><span>RENDERED FILM</span><h2>{filmError?'The film could not be loaded.':'The full render is being prepared.'}</h2><p>The complete sequence remains available in the interactive view.</p><button onClick={()=>setPresentation('interactive')}>Return to interactive sequence</button><button onClick={()=>setFilmRefresh(value=>value+1)}>Check film availability</button></div>}{presentation==='interactive'&&<><div className="fire-stage-caption"><span>CHAPTER {String(stageIndex+1).padStart(2,'0')} / {String(STAGES.length).padStart(2,'0')}</span><h2>{stage.id==='treatment'&&mode==='gradual'?'Finite source, calculated mass':stage.title}</h2><p>{stage.description}</p><div className="fire-coverage"><strong>Illustrated peat involvement: {(coverage*100).toFixed(0)}%</strong><span>{coverage>=.7?'Treatment trigger reached · 70%':'Treatment trigger · 70%'}</span></div></div><div className={`fire-evidence-badge ${view==='natural'?'is-story':''}`}><i/><div><strong>{view==='natural'?'Illustrated sequence':cacheFrame?(mode==='rapid'&&time>=55?'Accepted pre-treatment reference':'Accepted numerical field'):'Numerical field unavailable'}</strong><span>{view==='natural'?'Underground spread / water paths not calculated':cacheFrame?`${clock(cacheFrame.timeS)} physical time · ${cache!.domain.nx*cache!.domain.ny*cache!.domain.nz} cells · propagation unresolved`:'Switch to Natural cutaway to inspect the story'}</span></div></div>{view!=='natural'&&<div className="fire-field-legend"><span>{view==='temperature'?'Temperature · K':view==='oxygen'?'O₂ · mole fraction':'CO₂ · mole fraction'}</span><i/><div><span>{view==='temperature'?'273':0}</span><span>{view==='temperature'?'≥873':view==='oxygen'?'0.209':'0.5'}</span></div></div>}<div className="fire-scene-foot"><span>Drag to orbit · scroll to zoom</span><span>{view!=='natural'?'Accepted cells · open midplane':mode==='rapid'?'Rapid mode: illustrative conversion':'Gradual mode: finite source'}</span></div></>}</div>
        {presentation==='film'&&<div className="fire-film-reference">Rendered reference film · bundled 24-hour experiment. Readouts below follow that fixed reference; custom calculations remain in Interactive.</div>}<div className="fire-sequence-caption-bar"><span>{time>=69?'ASSUMED WATER PATHS':mode==='rapid'&&time>=55?'ILLUSTRATIVE CONVERSION':'PRESENTATION SCOPE'}</span><p>{gap}</p></div>
        <div className="fire-sequence-timeline"><button className="fire-play" aria-label={playing?'Pause fire sequence':'Play fire sequence'} onClick={play} disabled={presentation==='film'}>{playing?'Ⅱ':'▶'}</button><button className="fire-restart" aria-label="Restart fire sequence" onClick={()=>{seek(0);if(presentation==='interactive')setPlaying(true)}}>↶</button><div className="fire-timeline-track"><div><span>PRESENTATION TIME</span><strong>{time.toFixed(1)} <small>/ {DURATION} s</small></strong></div><input type="range" aria-label="Fire sequence time" min={0} max={DURATION} step={.1} value={time} onChange={event=>{setPlaying(false);seek(Number(event.target.value))}}/><div className="fire-stage-ticks">{STAGES.map(item=><button key={item.id} style={{width:`${(item.end-item.start)/DURATION*100}%`}} aria-label={`Jump to ${item.short}`} onClick={()=>{setPlaying(false);seek(item.start)}}>{item.start}</button>)}</div></div><label className="fire-speed">Speed<select aria-label="Fire sequence speed" value={speed} onChange={event=>{const value=Number(event.target.value);setSpeed(value);if(videoRef.current)videoRef.current.playbackRate=value}}>{[.5,1,1.5,2,3].map(value=><option key={value} value={value}>{value}×</option>)}</select></label><label className="fire-loop"><input type="checkbox" checked={loop} onChange={event=>setLoop(event.target.checked)}/> Loop</label></div>
        <p className="fire-timing-note">Base timing: setup and review 2.8× · release / inversion at 55–61 s plays 1:1 · full sequence 36 s at 1× playback.</p><div className="fire-evidence-strip"><div><span>Accepted physical time</span><strong>{cacheFrame?clock(cacheFrame.timeS):'Not loaded'}</strong></div><div><span>Calculated peak temperature</span><strong>{cacheFrame?.metrics?`${(cacheFrame.metrics.maxTemperatureK-273.15).toFixed(1)} °C`:'—'}</strong></div><div><span>Calculated fuel consumed</span><strong>{cacheFrame?.metrics?`${cacheFrame.metrics.reactedFuelKg.toPrecision(3)} kg`:'—'}</strong></div><div><span>Calculated dry ice remaining</span><strong>{cacheFrame?`${cacheFrame.dryIceKg.toFixed(4)} kg`:'—'}</strong></div><div><span>Field validation</span><strong>Not established</strong></div></div>
        <FireExperimentControls settings={settings} onSettings={setSettings} cache={displayCache} canRestore={!!bundledCache.current} onResult={value=>{if(validCache(value)){acceptedCacheRef.current=value;setCache(value);setCacheStatus(value.status==='completed'?'New accepted numerical history':'Accepted partial numerical history');setPlaying(false);setPresentation('interactive');seek(0);return true}return false}} onRestore={()=>{if(bundledCache.current){acceptedCacheRef.current=bundledCache.current;setCache(bundledCache.current);setCacheStatus('Bundled numerical history restored');setPlaying(false);setPresentation('interactive');seek(0)}}}/>
        <details className="fire-evidence-details"><summary>Layers, calculation provenance & limitations <span>{cacheStatus}</span></summary><div className="fire-layer-controls">{([['fire','Fire / smoke cues'],['gas','CO₂ tracers'],['water','Water illustration'],['anatomy','Tree / root context']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={layers[key]} onChange={event=>setLayers(old=>({...old,[key]:event.target.checked}))}/>{label}</label>)}</div><p>{stage.evidence}</p><p><strong>Underground propagation:</strong> {cache?.propagationResolved?'See the accepted numerical history and its stated resolution limits.':'Not resolved as a verified moving smoldering front in the current calculation. Natural-view spread is a prescribed illustration.'} No matched experiment establishes treatment success.</p><p><strong>Geometry:</strong> The natural view uses the layered reference scenery. The numerical experiment assumes surface-connected peat throughout the domain; its exposed cell values are shown without illustrative anatomy or actions.</p><p><strong>Source modes:</strong> Gradual mode uses accepted finite-source mass where available. Rapid mode is a prescribed visual conversion; numerical fields and readouts hold the pre-treatment reference after the intervention chapter. It is not a calculated rapid-conversion experiment. Neither the illustrated plate bending nor the drawn fracture paths establish a pressure-induced failure prediction.</p>{cache?.stopReason&&<p className="fire-cache-warning">Calculation limit: {cache.stopReason}</p>}{cache?.assumptions?.map((text,i)=><p key={i} className="fire-cache-assumption">{text}</p>)}</details>
      </section>
    </main><footer className="fire-sequence-footer"><span>Story geometry and solver evidence remain separate</span><span>90 s story · 36 s playback · SI numerical fields</span><span>Research visualization</span></footer>
  </div>
}
