import { ToolboxPortal } from './CinematicUI'
import { useEffect,useMemo,useRef,useState,type MutableRefObject } from 'react'
import { Canvas,useThree } from '@react-three/fiber'
import type { OrbitControls as Controls } from 'three-stdlib'
import { OrbitControls } from '@react-three/drei/core/OrbitControls.js'
import { DEFAULT_TENSILE,KRIMPEN_EVIDENCE,compareTensileObservations,parseTensileCsv,runTensileFracture,type TensileInputs,type TensileFrame,type TensileObservation } from '../mechanics/tensileFracture'
import { ModelSelector,type PhysicsWorkspace } from './ModelSelector'
import { ParameterSlider } from './ParameterSlider'
let savedTensileCamera:{position:number[];target:number[]}|undefined
function TensileCamera() {
 const {camera}=useThree(),controls=useRef<Controls>(null),initial=useRef(savedTensileCamera)
 useEffect(()=>{if(initial.current&&controls.current){camera.position.fromArray(initial.current.position);controls.current.target.fromArray(initial.current.target);controls.current.update()}},[camera])
 return <OrbitControls ref={controls} makeDefault enableDamping={false} target={[0.01,0,0]} minDistance={0.1} maxDistance={0.6} onChange={()=>{if(controls.current)savedTensileCamera={position:camera.position.toArray(),target:controls.current.target.toArray()}}}/>
}
export interface TensileSession {inputs:TensileInputs;frames:TensileFrame[];stage:number;observations:TensileObservation[];filename:string;testNotes:string;dataUse:string;magnification:number}
export default function PeatTensionLab({onWorkspace,onBack,session}:{onWorkspace:(v:PhysicsWorkspace)=>void;onBack:()=>void;session:MutableRefObject<TensileSession|undefined>}) {
 const saved=session.current
 const [inputs,setInputs]=useState(saved?.inputs??{...DEFAULT_TENSILE})
 const [frames,setFrames]=useState<TensileFrame[]>(saved?.frames??[])
 const [stage,setStage]=useState(saved?.stage??0)
 const [observations,setObservations]=useState<TensileObservation[]>(saved?.observations??[])
 const [filename,setFilename]=useState(saved?.filename??'')
 const [testNotes,setTestNotes]=useState(saved?.testNotes??''),[dataUse,setDataUse]=useState(saved?.dataUse??'unclassified')
 const [error,setError]=useState(''),[playing,setPlaying]=useState(false),[magnification,setMagnification]=useState(saved?.magnification??8)
 const input=useRef<HTMLInputElement>(null)
 useEffect(()=>{session.current={inputs,frames,stage,observations,filename,testNotes,dataUse,magnification}},[inputs,frames,stage,observations,filename,testNotes,dataUse,magnification,session])
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStage(old=>{if(old>=frames.length-1){setPlaying(false);return old};return old+1}),35);return()=>clearInterval(timer)},[playing,frames.length])
 const frame=frames[stage]
 const comparisonState=useMemo(()=>{if(!frames.length||!observations.length)return {result:null,error:''};try{return {result:compareTensileObservations(frames,observations),error:''}}catch(e){return {result:null,error:e instanceof Error?e.message:String(e)}}},[frames,observations])
 const comparison=comparisonState.result
 const update=(next:TensileInputs)=>{setInputs(next);setFrames([]);setStage(0);setPlaying(false);setError('')}
 const calculate=()=>{setPlaying(false);setStage(0);try{setFrames(runTensileFracture(inputs));setError('')}catch(e){setFrames([]);setError(e instanceof Error?e.message:String(e))}}
 const half=(inputs.lengthM+((frame?.extensionM??0)-(frame?.openingM??0))*magnification)/2
 const gap=(frame?.openingM??0)*magnification
 const download=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({format:'zombie-fire-tensile-coupon',inputs,evidence:KRIMPEN_EVIDENCE,frames,observations,observationFile:filename,testNotes,dataUse,comparison,comparisonError:comparisonState.error,scope:'One prescribed cohesive plane. Conditional mode-I force/separation; strength midpoint from reported range; stiffness and fracture energy assumed. No spatial fracture path, creep or field validation.'},null,2)],{type:'application/json'}));a.href=url;a.download='peat-tensile-coupon.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const maxForce=Math.max(1,...frames.map(f=>f.forceN),...observations.map(o=>o.forceN))
 const maxExtension=Math.max(1e-6,...frames.map(f=>f.extensionM),...observations.map(o=>o.extensionM))
 const curve=frames.slice(0,inputs.increments+1).map((f,i)=>`${i?'L':'M'}${45+f.extensionM/maxExtension*640},${130-f.forceN/maxForce*105}`).join(' ')
 return <div className="ops-shell">
  <ToolboxPortal extra><header className="ops-header"><div className="ops-brand"><strong>ZOMBIE FIRE</strong><span>LABORATORY FAILURE / MODE I</span></div><ModelSelector value="mechanics" onChange={onWorkspace}/><button className="ops-secondary" onClick={onBack}>Back to compression comparison</button></header></ToolboxPortal>
  <div className="ops-title"><div><span className="ops-eyebrow">KRIMPEN WOODY PEAT / DIRECT TENSION REFERENCE</span><h1>Tensile separation &amp; energy.</h1></div><span className="ops-status">{frame?.damage===1?'SEPARATED':frame?.damage?'SOFTENING':frames.length?'INTACT':'READY TO CALCULATE'}<i/></span></div>
  <main className="ops-main"><ToolboxPortal><aside className="ops-controls"><h2>Laboratory coupon</h2><p>100 mm long × 66 mm diameter. Horizontal tension; an assumed weak plane at the center. Free sides; imposed grip extension.</p>
    <ParameterSlider label="Tensile strength" value={inputs.strengthPa/1000} min={0.1} max={10} step={0.05} unit="kPa" defaultValue={4.25} note="4.25 = midpoint of reported unsubmerged 3.5–5 kPa range" onChange={v=>update({...inputs,strengthPa:v*1000})}/>
    <ParameterSlider label="Fracture energy" value={inputs.fractureEnergyJm2} min={0.2} max={100} step={0.1} unit="J/m²" defaultValue={5} note="Assumed; paired measurement unavailable" onChange={v=>update({...inputs,fractureEnergyJm2:v})}/>
    <ParameterSlider label="Bulk stiffness" value={inputs.youngsPa/1e6} min={0.1} max={10} step={0.1} unit="MPa" defaultValue={1} note="Assumed; not derived from peak strength" onChange={v=>update({...inputs,youngsPa:v*1e6})}/>
    <details className="ops-details"><summary>Developer tools · interface and mesh</summary><ParameterSlider label="Interface stiffness" value={inputs.interfaceStiffnessPam/1e9} min={0.01} max={10} step={0.01} unit="MPa/mm" defaultValue={0.1} note="Numerical elastic interface stiffness" onChange={v=>update({...inputs,interfaceStiffnessPam:v*1e9})}/><label>Bar elements<select aria-label="Tensile bar elements" value={inputs.elements} onChange={e=>update({...inputs,elements:Number(e.target.value)})}>{[2,4,8,32].map(n=><option key={n}>{n}</option>)}</select></label><ParameterSlider label="Tensile load increments" value={inputs.increments} min={20} max={400} step={20} unit="steps" defaultValue={100} onChange={v=>update({...inputs,increments:Math.round(v)})}/></details>
    <button className="ops-primary" onClick={calculate}>Calculate tensile fracture</button><button className="ops-secondary" onClick={()=>update({...DEFAULT_TENSILE})}>Reset tensile inputs</button><p>Physical edits discard the trajectory. Unstable snap-back and excessive bulk strain stop calculation.</p>{error&&<p className="ops-warning" role="alert">{error}</p>}
    <details className="ops-details"><summary>Peat evidence and applicability</summary><p>Krimpen woody peat; water/dry-mass ratio 460–570%; sampled 0.5–0.9 m below ground. Reported tests used 12% strain/h and gypsum tension caps. This rate-independent coupon omits suction evolution, consolidation history and creep.</p><p>Unsubmerged peaks: 3.5 and 5 kPa. Submerged peaks: 0 and 2 kPa. These are different conditions; the submerged interval is not a moisture slider or a strength law.</p><p><a href="https://doi.org/10.1680/jgere.17.00006" target="_blank" rel="noreferrer">O’Kelly (2017), reviewing Abebaw (2005)</a>. Full stress–opening curves and independent holdout data are still needed.</p></details>
  </aside></ToolboxPortal>
  <section className="ops-visual"><ToolboxPortal><div className="ops-toolbar"><span>Calculated opening · one prescribed cohesive plane</span><label className="ops-check">Display ×<select aria-label="Tensile display magnification" value={magnification} onChange={e=>setMagnification(Number(e.target.value))}>{[1,4,8,12].map(n=><option key={n}>{n}</option>)}</select></label></div></ToolboxPortal>
   <div className="ops-viewport"><div className="ops-scene-labels"><span>{frame?`Opening ${(frame.openingM*1000).toFixed(3)} mm`:'Press Calculate to obtain a trajectory'}<small>Displacement magnification changes appearance only</small></span></div>
    <Canvas frameloop="demand" camera={{position:[0.02,0.09,0.18],fov:40,near:0.001,far:10}}><color attach="background" args={['#000000']}/><ambientLight intensity={1.4}/><directionalLight position={[1,2,3]} intensity={2}/><TensileCamera/>
     {[-inputs.lengthM/2+half/2,-inputs.lengthM/2+half*1.5+gap].map((x,i)=><mesh key={i} position={[x,0,0]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[inputs.diameterM/2,inputs.diameterM/2,half,48]}/><meshStandardMaterial color={i?'#847257':'#9a8868'} roughness={1}/></mesh>)}
    </Canvas><div className="ops-scene-foot"><span>Peat-colored geometry · no root reinforcement</span><span>Bulk strain {((frame?.bulkStrain??0)*100).toFixed(3)}%</span></div></div>
   <div className="tensile-chart"><div><strong>Force–extension response</strong><span>Model line · measured points when imported</span></div><svg viewBox="0 0 740 157" role="img" aria-label="Tensile force in newtons against grip extension in millimeters"><path d="M45 18 V130 H685" fill="none" stroke="#6f8068"/><path d={curve} fill="none" stroke="#cedc9e" strokeWidth="2"/>{observations.map((o,i)=><circle key={i} cx={45+o.extensionM/maxExtension*640} cy={130-o.forceN/maxForce*105} r="3" fill="#cfac73"/>)}<text x="2" y="18">{maxForce.toFixed(1)} N</text><text x="45" y="150">0</text><text x="570" y="150">{(maxExtension*1000).toFixed(2)} mm extension</text>{frame&&<circle cx={45+frame.extensionM/maxExtension*640} cy={130-frame.forceN/maxForce*105} r="4" fill="#e8efdd"/>}</svg></div>
   <ToolboxPortal extra><div className="ops-telemetry"><article><h3>Fracture response</h3><dl><div><dt>Tensile force</dt><dd>{frame?.forceN.toFixed(3)??'—'} <small>N</small></dd></div><div><dt>Cohesive damage</dt><dd>{frame?.damage.toFixed(4)??'—'} <small>0–1</small></dd></div></dl></article><article><h3>Energy balance</h3><dl><div><dt>Dissipated in separation</dt><dd>{frame?.fractureDissipationJ.toExponential(3)??'—'} <small>J</small></dd></div><div><dt>Work − storage − dissipation</dt><dd>{frame?.energyResidualJ.toExponential(1)??'—'} <small>J</small></dd></div></dl></article></div></ToolboxPortal>
   <ToolboxPortal extra><div className="tensile-data"><button className="ops-secondary" disabled={!frames.length} onClick={()=>input.current?.click()}>Compare measured CSV</button><input ref={input} type="file" accept=".csv" hidden onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('CSV must be under 1 MB.');const points=parseTensileCsv(await file.text());compareTensileObservations(frames,points);setObservations(points);setFilename(file.name);setDataUse('unclassified');setTestNotes('');setError('')}catch(error){setError(error instanceof Error?error.message:String(error))}e.target.value=''}}/><p>{comparisonState.error|| (comparison?`${filename} · RMSE ${comparison.rmseN.toFixed(3)} N · peak error ${comparison.peakErrorN.toFixed(3)} N`:'CSV: extension_mm,force_N · increasing loading branch · no extrapolation.')}<br/>Range-based parameter choice is calibration context, not independent validation. Review specimen conditions and keep validation data separate from fitting.</p></div></ToolboxPortal>{observations.length>0&&<ToolboxPortal extra><div className="tensile-metadata"><label>Data use<select aria-label="Tensile observation data use" value={dataUse} onChange={e=>setDataUse(e.target.value)}><option value="unclassified">Unclassified</option><option value="calibration">Calibration / fitting</option><option value="holdout">Independent holdout (user declaration)</option></select></label><label>Specimen &amp; test notes<textarea aria-label="Tensile specimen and test notes" value={testNotes} onChange={e=>setTestNotes(e.target.value)} placeholder="Source, specimen ID, water content and basis, orientation, confinement, grip compliance, rate and measurement uncertainty"/></label></div></ToolboxPortal>}
  </section></main>
  <footer className="ops-playback"><div><button className="ops-primary" disabled={!frames.length} onClick={()=>{if(stage>=frames.length-1)setStage(0);setPlaying(v=>!v)}}>{playing?'Pause tensile replay':'Play tensile test'}</button><ToolboxPortal extra><button className="ops-secondary" disabled={!frames.length} onClick={download}>Export tensile results</button></ToolboxPortal></div><label className="ops-timeline">Load stage<output>{stage} / {Math.max(0,frames.length-1)} · {frame?.damage===1?'fully separated':frame?.damage?'softening':'intact'}</output><input aria-label="Tensile load stage" type="range" min={0} max={Math.max(0,frames.length-1)} value={stage} disabled={!frames.length} onChange={e=>{setPlaying(false);setStage(Number(e.target.value))}}/></label><p>Quasi-static stages; no failure-time prediction. Work is supplied by the test grips. CO₂ and fire are absent.</p></footer>
  <ToolboxPortal extra><div className="ops-scope">CONDITIONAL MODE-I FRACTURE · Finite energy and irreversible separation at a prescribed plane. Does not predict the spatial crack path, peat creep, mixed-mode failure or gas-driven field rupture. Independent experimental validation is pending.</div></ToolboxPortal>
 </div>
}
