/** Reproducible manual figure digitization; no simulated curves or raw-data claim. */
import {writeFile} from 'node:fs/promises'
const calibration={nativeRaster:{width:918,height:563},panelA:{x0:4,x34h:426,y0C:244,y600C:19},panelC:{x0:4,x34h:426,y0C:562,y600C:337},pointSelectionErrorPx:2,axisSelectionErrorPx:1}
const peakPixels=[
  {case:'MC10-natural',depthCm:7,x:43,y:22},{case:'MC10-natural',depthCm:11,x:91,y:35},{case:'MC10-natural',depthCm:15,x:162,y:51},{case:'MC10-natural',depthCm:19,x:247,y:80},{case:'MC10-natural',depthCm:23,x:326,y:108},
  {case:'MC35-natural',depthCm:7,x:25,y:384},{case:'MC35-natural',depthCm:11,x:66,y:350},{case:'MC35-natural',depthCm:15,x:115,y:359},{case:'MC35-natural',depthCm:19,x:177,y:367},{case:'MC35-natural',depthCm:23,x:247,y:391},
]
const points=peakPixels.map(p=>{
  const a=p.case==='MC10-natural'?calibration.panelA:calibration.panelC
  return {...p,timeH:(p.x-a.x0)/(a.x34h-a.x0)*34,temperatureC:(a.y0C-p.y)/(a.y0C-a.y600C)*600,extractionBoundTimeH:3/(a.x34h-a.x0)*34,extractionBoundTemperatureK:3/(a.y0C-a.y600C)*600}
})
const intervals=points.flatMap((p,i)=>{const previous=points[i-1];return !previous||previous.case!==p.case?[]:[{case:p.case,fromDepthCm:previous.depthCm,toDepthCm:p.depthCm,speedCmH:(p.depthCm-previous.depthCm)/(p.timeH-previous.timeH),definition:'sensor-depth separation / digitized temperature-peak arrival difference'}]})
const report={source:{title:'Huang & Rein (2017), measured Figure 3(a,c), page 910 / PDF page 4',doi:'10.1071/WF16198',pdf:'https://spiral.imperial.ac.uk/bitstreams/4eea3c58-c751-433e-ab02-69ad203f9e64/download',sha256:'e6e6b6f96266fae6154ff3c812b72c4e2059d07c94a23a5eb79c465cb6c26acf',imageObject:'/Im3',imageEncoding:'CMYK JPEG, 918 × 563; converted to RGB for inspection, original source cached unmodified'},method:'Manual peak coordinates selected in the native-resolution figure raster, with axis values checked against the rendered labeled PDF. Linear axis calibration. These are approximate extracted facts, not raw thermocouple traces or an averaged replicate.',calibration,cases:[{id:'MC10-natural',role:'designated baseline, no parameters fitted',moistureDryRatio:.1,wetDensityKgM3:135,dryDensityKgM3:135/1.1},{id:'MC35-natural',role:'same-study held-out condition; no calibration performed',moistureDryRatio:.35,wetDensityKgM3:150,dryDensityKgM3:150/1.35}],protocol:{geometryM:[.1,.1,.3],peat:'Commercial Irish Shamrock moss peat',heaterW:100,heaterDurationS:1800,heaterDepthM:.05,sensorDepthSpacingM:.02,scanHz:.1,replicates:'2–3 experiments; selected figure is a group of histories, not replicate mean',moistureTreatmentUncertaintyDryRatio:.05,densityTreatmentUncertaintyKgM3:5,sideInsulationThicknessM:.0127},points,intervals,uncertainty:'Conservative 3 pixel extraction bounds combine 2 pixel point selection and 1 pixel axis selection; not statistical confidence intervals. Experimental replicate temperature/time uncertainty is unavailable from Figure 3; Figure 4 spread error bars have not been extracted.',comparisonContract:{metrics:['peak temperature at each actual sensor','peak arrival time at each actual sensor','spread from differences of peak arrival'],engineeringLimits:{peakTemperatureAbsoluteK:40,peakArrivalRelative:.2,spreadRelative:.25},numericalRequirement:'Separately bound discretization errors to 5 K and 10% of the arrival/spread metric before interpreting physical discrepancy',basis:'Predeclared project engineering tolerances, not paper criteria or measurement uncertainty',fitStatus:'no calibration or retuning',comparisonStatus:'unrun: active .10 m cube, top Gaussian ignition and insulated bottom do not match this .30 m column with buried heater; fixed mesh also omits measured recession/shrinkage'},status:'measured figure evidence digitized; matched simulation comparison and uncertainty qualification remain incomplete'}
await writeFile('docs/review/peat-fem/C4-measured-peaks.json',JSON.stringify(report,null,2)+'\n')
await writeFile('docs/review/peat-fem/C4-measured-peaks.csv','case,depth_cm,time_h,temperature_C,extraction_bound_time_h,extraction_bound_temperature_K\n'+points.map(p=>[p.case,p.depthCm,p.timeH,p.temperatureC,p.extractionBoundTimeH,p.extractionBoundTemperatureK].join(',')).join('\n')+'\n')
console.log(JSON.stringify({points:points.length,cases:report.cases.length,status:report.status,maximumExtractionTimeH:points[0].extractionBoundTimeH,maximumExtractionTemperatureK:points[0].extractionBoundTemperatureK}))
