const initialDuration=process.platform==='win32'?10:120;const {app}=require('electron'),path=require('node:path'),fs=require('node:fs');const root=path.resolve(__dirname,'..');const folder=path.join(root,'work','coupled-validation');fs.mkdirSync(folder,{recursive:true});app.setPath('userData',fs.mkdtempSync(path.join(folder,'profile-')));app.getAppPath=()=>root;process.argv.push('--coupled');
if(process.platform!=='darwin'){app.commandLine.appendSwitch('use-angle','swiftshader');app.commandLine.appendSwitch('enable-unsafe-swiftshader')}
let peak=0;const memory=setInterval(()=>{peak=Math.max(peak,app.getAppMetrics().reduce((s,p)=>s+p.memory.workingSetSize*1024,0))},250),timeout=setTimeout(()=>finish('timeout'),180000);
function finish(error){clearInterval(memory);clearTimeout(timeout);console.log(error?'COUPLED_SMOKE_FAIL '+error:'COUPLED_SMOKE_PASS');app.exit(error?1:0)}
app.on('browser-window-created',(_,win)=>{win.webContents.once('did-finish-load',async()=>{try{const results=await win.webContents.executeJavaScript(`(async()=>{
const wait=async(p,name)=>{for(let i=0;i<1400;i++){if(p())return;await new Promise(r=>setTimeout(r,100))}throw new Error('Wait failed '+name+' '+document.body.innerText.slice(-2000))};const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);const set=(label,value)=>{const input=document.querySelector('input[aria-label="'+label+'"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(value));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))};
await wait(()=>button('Calculate coupled scenario'),'workspace');set('Simulation duration slider',${initialDuration});[...document.querySelectorAll('label')].find(l=>l.textContent.includes('Calculate same scenario with rigid pores')).querySelector('input').click();await new Promise(r=>setTimeout(r,100));button('Calculate coupled scenario').click();await wait(()=>button('Cancel calculation'),'running');
const fps=[];const sampler=setInterval(()=>{const n=Number(document.querySelector('canvas')?.dataset.fps);if(n)fps.push(n)},100);await wait(()=>document.body.textContent.includes('Complete ·'),'result');clearInterval(sampler);
const text=document.body.innerText;if(!text.includes('${initialDuration.toFixed(2)} s')||document.querySelector('[role="alert"]'))throw new Error('Run did not complete');const field=document.querySelector('select[aria-label="Coupled field"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(field,'pressurePa');field.dispatchEvent(new Event('change',{bubbles:true}));set('Coupled replay time',1);await new Promise(r=>setTimeout(r,100));if(!document.body.textContent.includes('2.00 s'))throw new Error('Replay not retained');
window.dispatchEvent(new CustomEvent('workspace-request',{detail:'mechanics'}));await wait(()=>document.body.textContent.includes('Load. Deform. Recover.'),'mechanics');window.dispatchEvent(new CustomEvent('workspace-request',{detail:'coupled'}));await wait(()=>document.querySelector('select[aria-label="Coupled field"]')?.value==='pressurePa','retained coupled controls');if(!document.body.textContent.includes('2.00 s'))throw new Error('Run lost across workspace');
set('Simulation duration slider',3600);await new Promise(r=>setTimeout(r,100));if(!document.querySelector('button')||document.querySelector('button[disabled]')?.textContent==='Cancel calculation')throw new Error('Input invalidation failed');button('Calculate coupled scenario').click();await wait(()=>button('Cancel calculation'),'cancel start');const start=performance.now();button('Cancel calculation').click();await wait(()=>button('Calculate coupled scenario'),'cancel finish');const cancelMs=performance.now()-start;
set('Simulation duration slider',10);await new Promise(r=>setTimeout(r,100));button('Calculate coupled scenario').click();await wait(()=>document.body.textContent.includes('Complete ·'),'final result');
// Check displayed model throughput against exported independent run metadata.
let exportedBlob;const createUrl=URL.createObjectURL,anchorClick=HTMLAnchorElement.prototype.click;URL.createObjectURL=function(blob){exportedBlob=blob;return createUrl.call(this,blob)};HTMLAnchorElement.prototype.click=function(){};button('Export calculation').click();URL.createObjectURL=createUrl;HTMLAnchorElement.prototype.click=anchorClick;const exported=JSON.parse(await exportedBlob.text());
for(const mode of ['rigid','coupled']){const selector=document.querySelector('select[aria-label="Coupled comparison"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(selector,mode);selector.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));const r=exported.runs[mode],expected=(r.frames.at(-1).timeS/(r.solveMs/1000)).toFixed(1)+' sim s / wall s';if(document.querySelector('.coupled-instruments strong')?.textContent!==expected)throw new Error('Wrong selected-model throughput');if(!document.body.textContent.includes('10.00 s'))throw new Error('Comparison changed physical replay time')}
let adapter=null;if(navigator.gpu){const a=await navigator.gpu.requestAdapter();if(a)adapter={info:{vendor:a.info.vendor,architecture:a.info.architecture,device:a.info.device,description:a.info.description},features:[...a.features],maxBufferSize:a.limits.maxBufferSize}}const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl2');if(!gl||gl.isContextLost())throw new Error('WebGL unavailable');return{cancelMs,fps,webgpu:adapter,webglRenderer:gl.getParameter(gl.RENDERER),resultText:document.body.innerText};})()`);
results.peakApplicationWorkingSetBytes=peak;results.date=new Date().toISOString();results.notes='Actual Electron processes on this host. Initial Preview duration is 120 s on macOS/Linux and 10 s on Windows software graphics. FPS sampled while calculation runs; cancel measured UI event-to-enabled control. Process working sets summed; shared pages may be counted twice, compressed/GPU allocations not fully attributed.';fs.writeFileSync(path.join(folder,'native-smoke.json'),JSON.stringify(results,null,2));await new Promise(r=>setTimeout(r,500));fs.writeFileSync(path.join(folder,'native-coupled.png'),(await win.webContents.capturePage()).toPNG());finish()}catch(e){finish(String(e))}})});require('../electron/main.cjs');
