import {createServer} from 'vite';import {writeFile,readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {cpus,totalmem} from 'node:os';
const server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});
try{
const{CoupledEngine}=await server.ssrLoadModule('/src/coupled/engine.ts'),{CoupledTransport,coupledScenario,DEFAULT_COUPLED}=await server.ssrLoadModule('/src/coupled/model.ts'),{R,gasU}=await server.ssrLoadModule('/src/coupled/thermodynamics.ts'),{PoroMechanics}=await server.ssrLoadModule('/src/coupled/mechanics.ts');
function box(n){const s=coupledScenario({...DEFAULT_COUPLED,dryIceKg:0,reaction:false,heaterW:0});s.domain={nx:4,ny:4,nz:n,widthM:1,lengthM:1,depthM:1};Object.assign(s.source,{centerXM:0.5,centerYM:0.5,centerDepthM:0.5});s.peatRegions=[];s.hotRegions=[];s.root.amountKgM3=0;s.soil.compaction=0;s.soil.moistureSaturation=0;s.soil.porosity=0.5;s.soil.intrinsicPermeabilityHorizontalM2=s.soil.intrinsicPermeabilityVerticalM2=1e-12;s.soilLayers=[{...s.soilLayers[0],thicknessM:1,dryDensityMultiplier:1,porosityOffset:0,moistureSaturationOffset:0,permeabilityMultiplier:1,thermalConductivityMultiplier:1}];s.atmosphere.waterVaporMoleFraction=0;s.atmosphere.deepTemperatureC=s.atmosphere.temperatureC;s.atmosphere.surfaceHeatTransferWm2K=s.atmosphere.bottomHeatTransferWm2K=0;return s}
const consolidation=[];
for(const [n,dt]of [[4,1],[8,0.5],[16,0.25],[8,1],[8,0.25],[4,0.25]]){
 const s=box(n);s.model.maxStepS=dt;const engine=new CoupledEngine({...DEFAULT_COUPLED,youngsPa:1e5,cap:false,roots:false,fracture:false},s),t=engine.transport,m=engine.mechanics,p=Float64Array.from(t.pressure,(_,i)=>100*Math.sin(Math.PI*(Math.floor(i/16)+0.5)/n/2));t.gasGravityMS2=0;engine.mechanical=m.solve(p);
 for(let i=0;i<t.n;i++){t.pore[i]+=0.8*t.volume*(engine.mechanical.strain[i*6]+engine.mechanical.strain[i*6+1]+engine.mechanical.strain[i*6+2]);const target=101325+p[i],total=t.totalGas(i),needed=target*t.pore[i]/(R*t.temperature[i]);for(let j=0;j<3;j++){const old=t.gas[j][i];t.gas[j][i]*=needed/total;t.energy[i]+=(t.gas[j][i]-old)*gasU(j,t.temperature[i])}}
 t.sealInitialState();const start=performance.now();engine.advance(10);const modulus=1e6*0.75/(1.25*0.5),storage=0.5/101325+0.8**2/modulus,diffusivity=1e-12/1.8e-5/storage,factor=Math.exp(-diffusivity*Math.PI**2/4*10);let error=0,rms=0;
 for(let i=0;i<t.n;i++){const expected=p[i]*factor,actual=t.pressure[i]-101325;error=Math.max(error,Math.abs(actual-expected));rms+=(actual-expected)**2}
 const row={nz:n,dt,solveMs:performance.now()-start,diffusivity,maxErrorPa:error,relativeAmplitudeError:error/100,rmsErrorPa:Math.sqrt(rms/t.n),mechanicalResidualN:engine.mechanical.residualN,massResidualKg:t.ledger.massResidualKg,energyResidualJ:t.ledger.energyResidualJ,mechanicalWorkResidualJ:engine.mechanicalBalanceJ};consolidation.push(row);console.log('consolidation',row);
 if(error>3)throw new Error('Consolidation exceeds predefined 3% amplitude threshold');
}
if(!(consolidation[2].maxErrorPa<consolidation[1].maxErrorPa&&consolidation[1].maxErrorPa<consolidation[0].maxErrorPa))throw new Error('Consolidation refinement failed');
const fracture=[];
for(const n of[4,6,8]){
 const material={youngsPa:1e6,poisson:0.25,densityKgM3:180,biot:1,fractureEnergyJm2:5},m=new PoroMechanics(n,n,n,1,1,1,Array(n**3).fill(material),0.25),start=performance.now();let result;
 try{for(let load=1;load<=5;load++){const pressure=Float64Array.from({length:n**3},(_,i)=>{const x=(i%n+0.5)/n-0.5,y=(Math.floor(i/n)%n+0.5)/n-0.5,z=(Math.floor(i/(n*n))+0.5)/n-0.5;return 400*load*Math.exp(-(x*x+y*y+z*z)/0.06)});result=m.solve(pressure,true)}
 const damaged=[];for(let i=0;i<m.n;i++)if(result.damage[i]>0.1)damaged.push(i);fracture.push({n,ell:0.25,spacing:1/n,elapsedMs:performance.now()-start,status:'complete',fractureJ:result.fractureJ,maxDamage:result.maxDamage,maxStrain:result.maxStrain,residualN:result.residualN,damagedCells:damaged});}
 catch(e){fracture.push({n,ell:0.25,elapsedMs:performance.now()-start,status:'limited',message:String(e)})}console.log('fracture',fracture.at(-1))
}
const performanceRecords=[];for(const fidelity of['preview','engineering','research']){const samples=[];let last;for(let repeat=0;repeat<3;repeat++){const start=performance.now(),e=new CoupledEngine({...DEFAULT_COUPLED,fidelity}),initialized=performance.now();e.advance(10);samples.push({setupMs:initialized-start,solveMs:performance.now()-initialized,rssBytes:process.memoryUsage().rss});last=e;}performanceRecords.push({fidelity,samples,simulatedS:10,maxPressurePa:Math.max(...last.transport.pressure),maxTemperatureK:Math.max(...last.transport.temperature),dryIceKg:last.transport.dryIce,ledger:last.transport.ledger,mechanicalBalanceJ:last.mechanicalBalanceJ,geostaticResidualN:last.mechanics.geostaticResidualN});console.log('performance',fidelity,samples)}
const sourceHashes={};for(const p of['model','mechanics','thermodynamics','engine','linear','cap'])sourceHashes[p]=createHash('sha256').update(await readFile('src/coupled/'+p+'.ts')).digest('hex');const report={createdAt:new Date().toISOString(),host:{cpu:cpus()[0].model,node:process.version,physicalMemoryBytes:totalmem()},acceptance:{massRelative:1e-9,thermalEnergyRelative:1e-8,equilibriumN:1e-4,consolidationAmplitudeError:0.03,consolidationRefinement:'strictly decreasing'},sourceHashes,consolidation,fracture,performanceRecords};await writeFile('examples/coupledValidation.json',JSON.stringify(report,null,2)+'\n');
}finally{await server.close()}
